// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrYCFD6__CWSujYktd9hqV58vkv09gSnw',
    appId: '1:410734864634:android:2ee9746e17827583444143',
    messagingSenderId: '410734864634',
    projectId: 'shop-management-25c23',
    storageBucket: 'shop-management-25c23.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOrdPOMEegzXyztPtleBgJd7-YE89nRHM',
    appId: '1:410734864634:ios:a89a2ee2b9ce480d444143',
    messagingSenderId: '410734864634',
    projectId: 'shop-management-25c23',
    storageBucket: 'shop-management-25c23.firebasestorage.app',
    androidClientId: '410734864634-8s1eptjplc3ud1trcmf5k39d8lfadlub.apps.googleusercontent.com',
    iosClientId: '410734864634-ip3oinnumdbbdq074mdh25r4d6qlneuc.apps.googleusercontent.com',
    iosBundleId: 'com.example.authentication',
  );

}